### ISSUE TITLE
MortgageETL+XGBoost.ipynb notebook fail running on CPU

### ISSUE THREAD

**Issue by nvliyuan** [NVIDIA/spark-rapids-examples#144]
we will hit exception because of schema mismatch
```
Tracker started, with env={DMLC_NUM_SERVER=0, DMLC_TRACKER_URI=XXXX, DMLC_TRACKER_PORT=XXXX, DMLC_NUM_WORKER=1024}
XXXARN TaskSetManager: Lost task 92.0 in stage 62.0 (TID 10523) (10.XX executor 254): org.apache.spark.sql.execution.QueryExecutionException: Parquet column cannot be converted in file hdfs://XXX:9000/datXXXXn/part-0XXXX711607e3ba72-c000.snappy.parquet. Column: [loan_age], Expected: float, Found: DOUBLE
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.nextIterator(FileScanRDD.scala:179)
	at org.apache.spark.sql.execution.datasources.FileScanRDD$$anon$1.hasNext(FileScanRDD.scala:93)
	at org.apache.spark.sql.execution.FileSourceScanExec$$anon$1.hasNext(DataSourceScanExec.scala:503)
```

**Comment by nvliyuan** [comment]
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/84758614/162213944-ad543bc7-f27b-47eb-87cd-111e8c03497c.png">

**Comment by nvliyuan** [comment]
not a bug, should not apply schema to parquet
