### ISSUE TITLE
dmlc/XGBoost train failed on NGC cluster, failed to set "tracker_conf"

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids-examples#242]
**Describe the bug**
FAILED to xgboost config `-rabitTrackerHost=127.0.0.1 ` on NGC cluster due to https://github.com/NVIDIA/spark-rapids-examples/blob/main/examples/XGBoost-Examples/utility/scala/src/com/nvidia/spark/examples/utility/XGBoostArgs.scala#L67

Can get `rabit_tracker_host -> 127.0.0.1` and train PASS if remove [#L67]( https://github.com/NVIDIA/spark-rapids-examples/blob/main/examples/XGBoost-Examples/utility/scala/src/com/nvidia/spark/examples/utility/XGBoostArgs.scala#L67)

related PR: https://github.com/NVIDIA/spark-rapids-examples/pull/175/

```
------ Training ------
22/11/08 02:00:16 INFO XGBoostSpark: Running XGBoost 2.0.0-SNAPSHOT with parameters:
rabit_timeout -> -1
seed -> 0
handle_invalid -> error
features_col -> features
label_col -> fare_amount
num_workers -> 2
eval_sets -> Map()
tree_limit -> 0
dmlc_worker_connect_retry -> 5
train_test_ratio -> 1.0
use_external_memory -> false
objective -> reg:squarederror
features_cols -> [Ljava.lang.String;@49153009
eval_metric -> rmse
num_round -> 25
missing -> NaN
rabit_ring_reduce_threshold -> 32768
tracker_conf -> TrackerConf(0,python,,)
tree_method -> gpu_hist
allow_non_zero_for_missing -> false
nthread -> 1
```
```
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger: Traceback (most recent call last):
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6670438512923624533.py", line 494, in <module>
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:     main()
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6670438512923624533.py", line 488, in main
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:     start_rabit_tracker(args)
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6670438512923624533.py", line 446, in start_rabit_tracker
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:     rabit = RabitTracker(
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:   File "/tmp/tracker6670438512923624533.py", line 209, in __init__
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger:     sock.bind((host_ip, port))
22/11/08 02:00:18 INFO RabitTracker$TrackerProcessLogger: OSError: [Errno 99] Cannot assign requested address
22/11/08 02:00:18 ERROR RabitTracker$TrackerProcessLogger: Tracker Process ends with exit code 1
22/11/08 02:00:19 INFO SparkContext: Starting job: collect at XGBoost.scala:414
22/11/08 02:00:19 INFO DAGScheduler: Registering RDD 6 (convert at NativeMethodAccessorImpl.java:0) as input to shuffle 0

....

22/11/08 02:01:00 ERROR XGBoostSpark: the job was aborted due to
ml.dmlc.xgboost4j.java.XGBoostError: XGBoostModel training failed.
        at ml.dmlc.xgboost4j.scala.spark.XGBoost$.trainDistributed(XGBoost.scala:418)
        at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:190)
        at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:36)
        at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)
        at com.nvidia.spark.examples.taxi.Main$.$anonfun$main$6(Main.scala:72)
        at com.nvidia.spark.examples.utility.Benchmark.time(Benchmark.scala:29)
        at com.nvidia.spark.examples.taxi.Main$.main(Main.scala:72)
        at com.nvidia.spark.examples.taxi.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:951)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1039)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1048)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
22/11/08 02:01:00 INFO SparkUI: Stopped Spark web UI at http://127.0.0.1:4040

```

**Steps/Code to reproduce bug**
On NGC cluster, run an xgboost train, e.g.
```
spark-submit  --master spark://127.0.0.1:7077 --conf spark.driver.host=127.0.0.1 --driver-memory 16G --executor-memory 32G --executor-cores 8 --conf spark.task.cpus=1 --conf spark.cores.max=16 --conf spark.local.dir=/raid/tmp --conf spark.eventLog.enabled=true --conf spark.rapids.cudfVersionOverride=true --conf spark.driver.extraClassPath=/test/rapids-4-spark.jar --conf spark.executor.extraClassPath=/test/rapids-4-spark.jar --conf spark.sql.broadcastTimeout=-1 --conf spark.sql.files.maxPartitionBytes=256MB --conf spark.sql.shuffle.partitions=128 --conf spark.network.timeout=600s --conf spark.locality.wait=0 --conf spark.shuffle.service.enabled=false --conf spark.hadoop.fs.s3a.access.key=spark --conf spark.hadoop.fs.s3a.secret.key=9cdf870fddf9c95bc791df6124f0eea8 --conf spark.hadoop.fs.s3a.endpoint=swiftstack-maglev.ngc.nvidia.com --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.driver.extraJavaOptions=-Dlog4jspark.root.logger=WARN,console --jars /test/xgboost4j.jar,/test/xgboost4j-spark.jar  --conf spark.plugins=com.nvidia.spark.SQLPlugin --conf spark.executor.resource.gpu.vendor=nvidia.com --conf spark.executor.resource.gpu.amount=1 --conf spark.executorEnv.LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 --conf spark.executorEnv.LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 --conf spark.task.resource.gpu.amount=0.1250 --conf spark.executor.extraJavaOptions=-Djava.io.tmpdir=/raid/tmp\ -Dai.rapids.cudf.prefer-pinned=true --conf spark.rapids.sql.concurrentGpuTasks=4 --conf spark.rapids.shuffle.maxMetadataSize=1MB --conf spark.rapids.shuffle.transport.enabled=true --conf spark.rapids.shuffle.compression.codec=none --conf spark.rapids.memory.pinnedPool.size=8G --conf spark.rapids.memory.host.spillStorageSize=16G --conf spark.rapids.memory.gpu.pool=ARENA --conf spark.rapids.memory.gpu.allocFraction=0.9 --conf spark.rapids.memory.gpu.maxAllocFraction=1 --conf spark.rapids.sql.batchSizeBytes=256MB --conf spark.rapids.sql.castFloatToString.enabled=true --conf spark.rapids.sql.castStringToFloat.enabled=true --conf spark.rapids.sql.castStringToInteger.enabled=true --conf spark.rapids.sql.variableFloatAgg.enabled=true --conf spark.rapids.sql.incompatibleOps.enabled=true  --class com.nvidia.spark.examples.taxi.Main --name taxi-E2E-GPU /sample-new.jar          -dataPath=rawTrain::s3a://spark-data/data/xgboost/raw_taxi/csv/train -dataPath=rawTrans::s3a://spark-data/data/xgboost/raw_taxi/csv/trans         -numRound=25 -overwrite=true -format=csv -rabitTrackerHost=127.0.0.1         -numWorkers=2 -modelPath=/tmp/models/taxi-E2E-GPU      -treeMethod=gpu_hist
```

**Expected behavior**
train get PASS

**Environment details (please complete the following information)**
 -  NGC, spark-standalone
 - configs as above "steps/Code to reproduce bug"

**Comment by NvTimLiu** [comment]
verified https://github.com/NVIDIA/spark-rapids-examples/pull/243 on NGC, close
