### ISSUE TITLE
databricks 

### ISSUE THREAD

**Issue by sauravdev** [NVIDIA/spark-rapids-examples#270]
**Describe the bug**
The databricks qualification & profiling doesn't work and throws following error 

java.lang.NoSuchMethodError: org.apache.spark.util.JsonProtocol$.sparkEventFromJson(Lorg/json4s/JsonAST$JValue;)Lorg/apache/spark/scheduler/SparkListenerEvent;
	at org.apache.spark.sql.rapids.tool.AppBase.$anonfun$processEvents$6(AppBase.scala:177)
	at org.apache.spark.sql.rapids.tool.AppBase.$anonfun$processEvents$6$adapted(AppBase.scala:174)
	at scala.collection.Iterator.find(Iterator.scala:995)
	at scala.collection.Iterator.find$(Iterator.scala:992)
	at scala.collection.AbstractIterator.find(Iterator.scala:1431)
	at org.apache.spark.sql.rapids.tool.AppBase.$anonfun$processEvents$5(AppBase.scala:174)
	at org.apache.spark.util.Utils$.tryWithResource(Utils.scala:3098)
	at org.apache.spark.sql.rapids.tool.AppBase.$anonfun$processEvents$3(AppBase.scala:170)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at org.apache.spark.sql.rapids.tool.AppBase.processEvents(AppBase.scala:169)
	at org.apache.spark.sql.rapids.tool.profiling.ApplicationInfo.<init>(ApplicationInfo.scala:226)
	at com.nvidia.spark.rapids.tool.profiling.Profiler.com$nvidia$spark$rapids$tool$profiling$Profiler$$createApp(Profiler.scala:259)
	at com.nvidia.spark.rapids.tool.profiling.Profiler$ProfileProcessThread$1.run(Profiler.scala:222)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Steps/Code to reproduce bug**
As per https://github.com/NVIDIA/spark-rapids-examples/tree/main/tools/databricks

java -Xmx10g -cp /tmp/rapids-4-spark-tools.jar:/databricks/jars/* com.nvidia.spark.rapids.tool.profiling.ProfileMain --csv --auto-tuner /dbfs/FileStore/logs

**Environment details (please complete the following information)**
 - Databricks 11.3 LTS

P.S: After replacing /databricks/jars/* with a fresh donwload of Spark jars this works fine.

**Comment by GaryShen2008** [comment]
Hi @mattahrens, can you help to investigate this issue about the qualification and profiling tools on Databricks 11.3?
Not sure if we have supported DB 11.3.

**Comment by mattahrens** [comment]
Spark RAPIDS isn't fully supported on Databricks 11.3 yet.  It appears the exception is caused by a backwards-incompatible change in the Spark JsonProtocol class in Databricks 11.3.

The tools notebooks work correctly Databricks 10.4 which we have fully validated.  @sauravdev: please try again with a Databricks 10.4 cluster and let me know if the issue is seen with that version.

We can keep this issue open to track the Databricks 11.3 compatibility changes needed for Spark RAPIDS tools.

**Comment by sauravdev** [comment]
Thanks @mattahrens  I have made it work in 11.3 as well, here is the changes code https://github.com/sauravdev/SparkRapids/tree/main/tools/databricks , but it does not use databricks jars hence we can keep it open to track full 11.3 support.
