### ISSUE TITLE
[BUG] cuspatial python tests failed libtiff.so.5: cannot open shared object file

### ISSUE THREAD

**Issue by pxLi** [NVIDIA/spark-rapids-examples#271]
**Describe the bug**
failed in internal CI examples-udf-cuSpatial, ID: 141,140

`libtiff.so.5: cannot open shared object file: No such file or directory`

```
18:35:58  23/01/19 10:35:58 WARN TaskSetManager: Lost task 0.0 in stage 1.0 (TID 1) (10.233.75.132 executor 0): org.apache.spark.SparkException: Task failed while writing rows.
18:35:58  	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:333)
18:35:58  	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$write$15(GpuFileFormatWriter.scala:246)
18:35:58  	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
18:35:58  	at org.apache.spark.scheduler.Task.run(Task.scala:131)
18:35:58  	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
18:35:58  	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
18:35:58  	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
18:35:58  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
18:35:58  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
18:35:58  	at java.lang.Thread.run(Thread.java:750)
18:35:58  Caused by: java.lang.UnsatisfiedLinkError: /tmp/spatialudfjni772751318704332126.so: libtiff.so.5: cannot open shared object file: No such file or directory
18:35:58  	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
18:35:58  	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
18:35:58  	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
18:35:58  	at java.lang.Runtime.load0(Runtime.java:811)
18:35:58  	at java.lang.System.load(System.java:1088)
18:35:58  	at com.nvidia.spark.rapids.udf.UDFNativeLoader.ensureLoaded(UDFNativeLoader.java:39)
18:35:58  	at com.nvidia.spark.rapids.udf.PointInPolygon.evaluateColumnar(PointInPolygon.java:128)
18:35:58  	at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$4(GpuUserDefinedFunction.scala:59)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
18:35:58  	at org.apache.spark.sql.rapids.GpuScalaUDF.withResource(GpuScalaUDF.scala:30)
18:35:58  	at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$2(GpuUserDefinedFunction.scala:57)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:46)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:44)
18:35:58  	at org.apache.spark.sql.rapids.GpuScalaUDF.withResource(GpuScalaUDF.scala:30)
18:35:58  	at com.nvidia.spark.rapids.GpuUserDefinedFunction.columnarEval(GpuUserDefinedFunction.scala:55)
18:35:58  	at com.nvidia.spark.rapids.GpuUserDefinedFunction.columnarEval$(GpuUserDefinedFunction.scala:53)
18:35:58  	at org.apache.spark.sql.rapids.GpuScalaUDF.columnarEval(GpuScalaUDF.scala:30)
18:35:58  	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
18:35:58  	at com.nvidia.spark.rapids.GpuAlias.columnarEval(namedExpressions.scala:109)
18:35:58  	at com.nvidia.spark.rapids.RapidsPluginImplicits$ReallyAGpuExpression.columnarEval(implicits.scala:34)
18:35:58  	at com.nvidia.spark.rapids.GpuExpressionsUtils$.columnarEvalToColumn(GpuExpressions.scala:94)
18:35:58  	at com.nvidia.spark.rapids.GpuProjectExec$.projectSingle(basicPhysicalOperators.scala:108)
18:35:58  	at com.nvidia.spark.rapids.GpuProjectExec$.$anonfun$project$1(basicPhysicalOperators.scala:115)
18:35:58  	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1(implicits.scala:216)
18:35:58  	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.$anonfun$safeMap$1$adapted(implicits.scala:213)
18:35:58  	at scala.collection.immutable.List.foreach(List.scala:392)
18:35:58  	at com.nvidia.spark.rapids.RapidsPluginImplicits$MapsSafely.safeMap(implicits.scala:213)
18:35:58  	at com.nvidia.spark.rapids.RapidsPluginImplicits$AutoCloseableProducingSeq.safeMap(implicits.scala:248)
18:35:58  	at com.nvidia.spark.rapids.GpuProjectExec$.project(basicPhysicalOperators.scala:115)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$tieredProject$1(basicPhysicalOperators.scala:335)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.withResource(basicPhysicalOperators.scala:286)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.recurse$1(basicPhysicalOperators.scala:334)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.tieredProject(basicPhysicalOperators.scala:354)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$tieredProjectAndClose$2(basicPhysicalOperators.scala:360)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.withResource(basicPhysicalOperators.scala:286)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.$anonfun$tieredProjectAndClose$1(basicPhysicalOperators.scala:359)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource(Arm.scala:28)
18:35:58  	at com.nvidia.spark.rapids.Arm.withResource$(Arm.scala:26)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.withResource(basicPhysicalOperators.scala:286)
18:35:58  	at com.nvidia.spark.rapids.GpuTieredProject.tieredProjectAndClose(basicPhysicalOperators.scala:358)
18:35:58  	at com.nvidia.spark.rapids.GpuProjectExec.$anonfun$doExecuteColumnar$1(basicPhysicalOperators.scala:177)
18:35:58  	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
18:35:58  	at org.apache.spark.sql.rapids.GpuFileFormatDataWriter.writeWithIterator(GpuFileFormatDataWriter.scala:87)
18:35:58  	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.$anonfun$executeTask$1(GpuFileFormatWriter.scala:320)
18:35:58  	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1473)
18:35:58  	at org.apache.spark.sql.rapids.GpuFileFormatWriter$.executeTask(GpuFileFormatWriter.scala:327)
18:35:58  	... 9 more
```

**Steps/Code to reproduce bug**
Please provide a list of steps or a code sample to reproduce the issue.
Avoid posting private or sensitive data.

**Expected behavior**
Pass the test

**Comment by GaryShen2008** [comment]
It might be caused because we updated to use v23.02 of Rapids libraries by https://github.com/NVIDIA/spark-rapids-examples/pull/267.
If so, let's roll back to the original version.
We just need to provide one example to show the case. Don't need to catch up the latest version of Rapids.
@NvTimLiu can you verify if it works with the original version?

**Comment by NvTimLiu** [comment]
After roll back to 22.12, `conda install  libcuspatial=22.12` would also FAILED if we use 22.12 (for dependency jars and libcuspatial ), so we update to 23.02
https://nvidia.slack.com/archives/C01ARJSMXLH/p1673103539755199?thread_ts=1673087330.208399&cid=C01ARJSMXLH
Just rolled back to 22.12, the failure was the still as what we met before


[cuspatial](https://github.com/rapidsai/cuspatial): install libcuspatial
```
# Install libcuspatial from conda
conda install -c rapidsai-nightly -c nvidia -c conda-forge -c defaults libcuspatial=22.12
```
```
12:59:07  Solving environment: ...working... 
Building graph of deps:   0%|          | 0/7 [00:00<?, ?it/s]
Examining @/linux-64::__glibc==2.27=0:   0%|          | 0/7 [00:00<?, ?it/s]
Examining @/linux-64::__archspec==1=x86_64:  14%|█▍        | 1/7 [00:00<00:00, 2516.08it/s]
Examining python=3.8:  29%|██▊       | 2/7 [00:00<00:00, 3818.21it/s]                      
Examining libcuspatial=22.12:  43%|████▎     | 3/7 [00:01<00:02,  1.51it/s]
Examining libcuspatial=22.12:  57%|█████▋    | 4/7 [00:01<00:01,  2.02it/s]
Examining @/linux-64::__linux==5.4.0=0:  57%|█████▋    | 4/7 [00:02<00:01,  2.02it/s]
Examining @/linux-64::__cuda==11.6=0:  71%|███████▏  | 5/7 [00:02<00:00,  2.02it/s]  
Examining @/linux-64::__unix==0=0:  86%|████████▌ | 6/7 [00:02<00:00,  2.02it/s]   
                                                                                

Determining conflicts:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conflict for libcuspatial __glibc python:   0%|          | 0/7 [00:00<?, ?it/s]
Examining conflict for libcuspatial python:  14%|█▍        | 1/7 [00:00<00:01,  4.43it/s]
Examining conflict for libcuspatial python:  29%|██▊       | 2/7 [00:00<00:00,  8.85it/s]
                                                                                         
12:59:07  Found conflicts! Looking for incompatible packages.
12:59:07  This can take several minutes.  Press CTRL-C to abort.
12:59:07  failed
12:59:07  
12:59:07  UnsatisfiableError: The following specifications were found to be incompatible with each other:
12:59:07  
12:59:07  Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:
12:59:07  
12:59:07    - feature:/linux-64::__glibc==2.27=0
12:59:07    - libcuspatial=22.12 -> cudatoolkit[version='>=11,<12.0a0'] -> __glibc[version='>=2.17,<3.0.a0']
12:59:07    - python=3.8 -> libgcc-ng[version='>=10.3.0'] -> __glibc[version='>=2.17']
12:59:07  
12:59:07  Your installed version is: 2.27
12:59:07  
12:59:07  
12:59:09  [Pipeline] }

```


Suppose this is a symbol link issue for the spatialudfjni,  @nvliyuan please help to take a look? 

```
18:35:59  Caused by: java.lang.UnsatisfiedLinkError: /tmp/spatialudfjni1021127067917338628.so: libtiff.so.5: cannot open shared object file: No such file or directory
18:35:59  	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
18:35:59  	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
18:35:59  	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
18:35:59  	at java.lang.Runtime.load0(Runtime.java:811)
18:35:59  	at java.lang.System.load(System.java:1088)
18:35:59  	at com.nvidia.spark.rapids.udf.UDFNativeLoader.ensureLoaded(UDFNativeLoader.java:39)
 (edited) 
```

**Comment by NvTimLiu** [comment]
Conda dependency is `libtiff.so.6 : Version 4.5.0`, but libcuspatial.so build/link against `libtiff.so.5`


conda dependency is `libtiff.so.6 : Version 4.5.0`  

```
conda install -c rapidsai-nightly -c nvidia -c conda-forge -c defaults libcuspatial=23.02 -y --> 
   [2023-01-27T10:28:07.066Z]     libtiff-4.5.0              |       h6adf6a1_2         397 KB  conda-forge

ll /root/miniconda3/lib/libtif* lrwxrwxrwx 1 root root     16 Jan 30 06:18 /root/miniconda3/lib/libtiff.so -> libtiff.so.6.0.0* -->
    lrwxrwxrwx 1 root root     16 Jan 30 06:18 /root/miniconda3/lib/libtiff.so.6 -> libtiff.so.6.0.0*
    -rwxrwxr-x 2 root root 618936 Jan 15 21:25 /root/miniconda3/lib/libtiff.so.6.0.0*
    lrwxrwxrwx 1 root root     18 Jan 30 06:18 /root/miniconda3/lib/libtiffxx.so -> libtiffxx.so.6.0.0*
    lrwxrwxrwx 1 root root     18 Jan 30 06:18 /root/miniconda3/lib/libtiffxx.so.6 -> libtiffxx.so.6.0.0*
    -rwxrwxr-x 2 root root  17232 Jan 15 21:25 /root/miniconda3/lib/libtiffxx.so.6.0.0*

strings /root/miniconda3/lib/libtiff.so.6.0.0 | grep 4.5.0 -->
    LIBTIFF, Version 4.5.0
```

While libcuspatial.so build/link against `libtiff.so.5`
```

ldd /root/miniconda3/lib/libcuspatial.so -->
       ....
       libtiff.so.5 => not found
        libnss3.so => /root/miniconda3/lib/./././libnss3.so (0x00007fc88f81a000)

Caused by: java.lang.UnsatisfiedLinkError: /tmp/spatialudfjni8140331364676685671.so: libtiff.so.5: cannot open shared object file: No such file or directory
```

**Comment by NvTimLiu** [comment]
Reported issue to GitHub/cuSpatial : https://github.com/rapidsai/cuspatial/issues/881

**Comment by nvliyuan** [comment]
close since we target cuspatial demo to specific plugin version.
