### ISSUE TITLE
Cannot run CPU based version of Rapids XGBoost examples of Taxi notebooks

### ISSUE THREAD

**Issue by vonodiripsa** [NVIDIA/spark-rapids-examples#29]
**Describe the bug**
If you follow comments from GPU examples of NY Taxi notebooks (scala, python) from https://github.com/NVIDIA/spark-rapids-examples/tree/branch-21.08/examples/taxi/notebooks
The notebooks are always failing.
For GPU/CPU comparison we need to have a working version on the notebooks

**Steps/Code to reproduce bug**
Take a notebook from https://github.com/NVIDIA/spark-rapids-examples/tree/branch-21.08/examples/taxi/notebooks substitute GPU code with CPU code (from comments). The code is failing on fit method

**Expected behavior**
The CPU version of notebooks should run

**Environment details (please complete the following information)**
 Synapse notebooks. Should run in notebook environment

**Comment by GaryShen2008** [comment]
@wbo4958 Could you help to verify the CPU code of Taxi?

**Comment by vonodiripsa** [comment]
I am attaching my notebook which is failing in xgbRegressor.fit(trainSe
[XGBoostRegressionTaxiCPU.zip](https://github.com/NVIDIA/spark-rapids-examples/files/7360948/XGBoostRegressionTaxiCPU.zip)
t)

**Comment by vonodiripsa** [comment]
Sorry, I took old version. I am attaching the correct notebook.
[XGBoostClassificationTaxiCPU.zip](https://github.com/NVIDIA/spark-rapids-examples/files/7368145/XGBoostClassificationTaxiCPU.zip)
 This is the error:

java.lang.IllegalArgumentException: features does not exist. Available: vendorID, passengerCount, tripDistance, pickupLongitude, pickupLatitude, rateCodeID, storeAndFwdFlag, dropoffLongitude, dropoffLatitude, fareAmount
  at org.apache.spark.sql.types.StructType.

$anonfun$apply$1(StructType.scala:278)

  at scala.collection.MapLike.getOrElse(MapLike.scala:131)

  at scala.collection.MapLike.getOrElse$(MapLike.scala:129)

  at scala.collection.AbstractMap.getOrElse(Map.scala:63)

  at org.apache.spark.sql.types.StructType.apply(StructType.scala:277)

  at org.apache.spark.ml.util.SchemaUtils$.checkColumnType(SchemaUtils.scala:42)

  at org.apache.spark.ml.PredictorParams.validateAndTransformSchema(Predictor.scala:52)

  at org.apache.spark.ml.PredictorParams.validateAndTransformSchema$(Predictor.scala:47)

  at org.apache.spark.ml.classification.Classifier.org$apache$spark$ml$classification$ClassifierParams$$super$validateAndTransformSchema(Classifier.scala:73)

  at org.apache.spark.ml.classification.ClassifierParams.validateAndTransformSchema(Classifier.scala:43)

  at org.apache.spark.ml.classification.ClassifierParams.validateAndTransformSchema$(Classifier.scala:39)

  at org.apache.spark.ml.classification.ProbabilisticClassifier.org$apache$spark$ml$classification$ProbabilisticClassifierParams$$super$validateAndTransformSchema(ProbabilisticClassifier.scala:51)

  at org.apache.spark.ml.classification.ProbabilisticClassifierParams.validateAndTransformSchema(ProbabilisticClassifier.scala:38)

  at org.apache.spark.ml.classification.ProbabilisticClassifierParams.validateAndTransformSchema$(ProbabilisticClassifier.scala:34)

  at org.apache.spark.ml.classification.ProbabilisticClassifier.validateAndTransformSchema(ProbabilisticClassifier.scala:51)

  at org.apache.spark.ml.Predictor.transformSchema(Predictor.scala:177)

  at org.apache.spark.ml.PipelineStage.transformSchema(Pipeline.scala:71)

  at org.apache.spark.ml.Predictor.fit(Predictor.scala:133)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.fit(XGBoostClassifier.scala:171)

  at $anonfun$xgbClassificationModel$1(<console>:46)

  at Benchmark$.time(<console>:42)

**Comment by wbo4958** [comment]
Hi @vonodiripsa, Since you were trying to train by CPU, so you should not use "setFeaturesCols" API, instead, you should follow the CPU way, pls find here https://xgboost.readthedocs.io/en/latest/jvm/xgboost4j_spark_tutorial.html#build-an-ml-application-with-xgboost4j-spark

**Comment by vonodiripsa** [comment]
@wbo4958 sorry, I don't understand. I am not using "setFeaturesCols" API (check my XGBoostClassificationTaxiCPU.zip). I am following notebook guidance how to run it on CPU. Do you have it running on CPU?

**Comment by wbo4958** [comment]
@vonodiripsa pls check these code carefully

CPU version reqires an extra step before fitting data to classifier, using `VectorAssembler` to assemble all feature columns into one column. The following code snip shows how to do the vectorizing.

```scala
object Vectorize {
  def apply(df: DataFrame, featureNames: Seq[String], labelName: String): DataFrame = {
    val toFloat = df.schema.map(f => col(f.name).cast(FloatType))
    new VectorAssembler()
      .setInputCols(featureNames.toArray)
      .setOutputCol("features")
      .transform(df.select(toFloat:_*))
      .select(col("features"), col(labelName))
  }
}

trainSet = Vectorize(trainSet, featureCols, labelName)
evalSet = Vectorize(evalSet, featureCols, labelName)
transSet = Vectorize(transSet, featureCols, labelName)

```

Fortunately `VectorAssembler` is not needed for GPU version. Just fit the loaded data directly to XGBoostClassifier.

**Comment by vonodiripsa** [comment]
@wbo4958 You probably thinking that it is in python, It is scala:

trainSet = Vectorize(trainSet, featureCols, labelName) failed with

error: reassignment to val
       trainSet = Vectorize(trainSet, featureNames, labelColName)

If I use
       val trainSetOut = Vectorize(trainSet, featureNames, labelColName) then

xgbClassifier.fit(trainSetOut) failed with:

java.lang.IllegalArgumentException: requirement failed: Classifier found max label value = 70.5 but requires integers in range [0, ... 2147483647)
  at scala.Predef$.require(Predef.scala:281)

  at org.apache.spark.ml.classification.Classifier.getNumClasses(Classifier.scala:151)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:193)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.train(XGBoostClassifier.scala:41)

  at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostClassifier.fit(XGBoostClassifier.scala:171)

  at $anonfun$xgbClassificationModel$1(<console>:46)

  at Benchmark$.time(<console>:42)

**Comment by vonodiripsa** [comment]
@wbo4958 Now the error after
defined object Vectorize
trainSet1: org.apache.spark.sql.DataFrame = [features: vector, fareAmount: float]
evalSet1: org.apache.spark.sql.DataFrame = [features: vector, fareAmount: float]
transSet1: org.apache.spark.sql.DataFrame = [features: vector, fareAmount: float]


val (model, _) = Benchmark.time("train") {
  xgbRegressor.fit(trainSet1)
}


org.apache.spark.sql.AnalysisException: cannot resolve '`features`' given input columns: [dropoffLatitude, dropoffLongitude, fareAmount, passengerCount, pickupLatitude, pickupLongitude, rateCodeID, storeAndFwdFlag, tripDistance, vendorID];
'Project [cast(fareAmount#29 as float) AS fareAmount#209, 'features, cast(1.0 as float) AS CAST(1.0 AS FLOAT)#206, cast(-1 as int) AS CAST(-1 AS INT)#207, cast(NaN as float) AS CAST(NaN AS FLOAT)#208]

+- Relation[vendorID#20,passengerCount#21,tripDistance#22,pickupLongitude#23,pickupLatitude#24,rateCodeID#25,storeAndFwdFlag#26,dropoffLongitude#27,dropoffLatitude#28,fareAmount#29] parquet



  at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:155)

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$$nestedInanonfun$checkAnalysis$1$2.applyOrElse(CheckAnalysis.scala:152)

  at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformUp$2(TreeNode.scala:342)

  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:74)

  at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:342)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$transformExpressionsUp$1(QueryPlan.scala:104)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$1(QueryPlan.scala:116)

  at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:74)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpression$1(QueryPlan.scala:116)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:127)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$3(QueryPlan.scala:132)

  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)

  at scala.collection.immutable.List.foreach(List.scala:392)

  at scala.collection.TraversableLike.map(TraversableLike.scala:238)

  at scala.collection.TraversableLike.map$(TraversableLike.scala:231)

  at scala.collection.immutable.List.map(List.scala:298)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.recursiveTransform$1(QueryPlan.scala:132)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.$anonfun$mapExpressions$4(QueryPlan.scala:137)

  at org.apache.spark.sql.catalyst.trees.TreeNode.mapProductIterator(TreeNode.scala:244)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.mapExpressions(QueryPlan.scala:137)

  at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:104)

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1(CheckAnalysis.scala:152)

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.$anonfun$checkAnalysis$1$adapted(CheckAnalysis.scala:93)

  at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:184)

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis(CheckAnalysis.scala:93)

  at org.apache.spark.sql.catalyst.analysis.CheckAnalysis.checkAnalysis$(CheckAnalysis.scala:90)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:155)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.$anonfun$executeAndCheck$1(Analyzer.scala:176)

  at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.markInAnalyzer(AnalysisHelper.scala:228)

  at org.apache.spark.sql.catalyst.analysis.Analyzer.executeAndCheck(Analyzer.scala:173)

  at org.apache.spark.sql.execution.QueryExecution.$anonfun$analyzed$1(QueryExecution.scala:74)

  at org.apache.spark.sql.catalyst.QueryPlanningTracker.measurePhase(QueryPlanningTracker.scala:111)

  at org.apache.spark.sql.execution.QueryExecution.$anonfun$executePhase$1(QueryExecution.scala:144)

  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)

  at org.apache.spark.sql.execution.QueryExecution.executePhase(QueryExecution.scala:144)

  at org.apache.spark.sql.execution.QueryExecution.analyzed$lzycompute(QueryExecution.scala:74)

  at org.apache.spark.sql.execution.QueryExecution.analyzed(QueryExecution.scala:72)

  at org.apache.spark.sql.execution.QueryExecution.assertAnalyzed(QueryExecution.scala:64)

  at org.apache.spark.sql.Dataset$.$anonfun$ofRows$1(Dataset.scala:90)

  at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)

  at org.apache.spark.sql.Dataset$.ofRows(Dataset.scala:88)

  at org.apache.spark.sql.Dataset.withPlan(Dataset.scala:3715)

  at org.apache.spark.sql.Dataset.select(Dataset.scala:1462)

  at ml.dmlc.xgboost4j.scala.spark.DataUtils$.$anonfun$convertDataFrameToXGBLabeledPointRDDs$3(DataUtils.scala:122)

  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)

  at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)

  at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)

  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)

  at scala.collection.TraversableLike.map(TraversableLike.scala:238)

  at scala.collection.TraversableLike.map$(TraversableLike.scala:231)

  at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)

  at ml.dmlc.xgboost4j.scala.spark.DataUtils$.convertDataFrameToXGBLabeledPointRDDs(DataUtils.scala:121)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.$anonfun$train$1(XGBoostRegressor.scala:207)

  at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)

  at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)

  at scala.collection.TraversableLike.map(TraversableLike.scala:238)

  at scala.collection.TraversableLike.map$(TraversableLike.scala:231)

  at scala.collection.AbstractTraversable.map(Traversable.scala:108)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:203)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.train(XGBoostRegressor.scala:43)

  at org.apache.spark.ml.Predictor.fit(Predictor.scala:151)

  at ml.dmlc.xgboost4j.scala.spark.XGBoostRegressor.fit(XGBoostRegressor.scala:171)

  at $anonfun$model$1(<console>:48)

  at Benchmark$.time(<console>:43)

**Comment by wbo4958** [comment]
@vonodiripsa I don't know where you get the note from, but it's not the correct one. Could you pls follow up https://github.com/NVIDIA/spark-xgboost-examples/blob/spark-3/examples/notebooks/scala/taxi-gpu.ipynb

**Comment by vonodiripsa** [comment]
@wbo4958 Please check the issue description it has the location. Is it possible to create working CPU version of the notebook?

**Comment by vonodiripsa** [comment]
It works with taxi-small dataset. On Monday I will try the notebook against transformed dataset (after https://github.com/NVIDIA/spark-rapids-examples/blob/branch-21.08/examples/taxi/notebooks/python/Taxi_ETL.ipynb). If it will work we could close the issue.

**Comment by vonodiripsa** [comment]
It is fine with me, because I was just doing time comparison.
At the same time I've noticed that GPU version is not returning the same results like CPU. But I think, it is another issue and this one could be closed.

**Comment by wbo4958** [comment]
Thx @vonodiripsa, Is there other issue you have reported for the different result from CPU and GPU?

**Comment by wbo4958** [comment]
Let's close this issue
