### ISSUE TITLE
cuSpatial integration test FAILED with Unsatisfied symbol: null_count()

### ISSUE THREAD

**Issue by NvTimLiu** [NVIDIA/spark-rapids-examples#302]
**Describe the bug**
cuSpatial integration test FAILED with Unsatisfied symbol: null_count(), executor log as below: Unsatisfied symbol: null_count()  as below:

```
ERROR Utils: Aborting task
java.lang.UnsatisfiedLinkError: /tmp/spatialudfjni2902319186678461993.so: /root/miniconda3/lib/libcuspatial.so: undefined symbol: _ZNK4cudf6detail16column_view_base10null_countEv
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
        at java.lang.Runtime.load0(Runtime.java:811)
        at java.lang.System.load(System.java:1088)
        at com.nvidia.spark.rapids.udf.UDFNativeLoader.ensureLoaded(UDFNativeLoader.java:39)
        at com.nvidia.spark.rapids.udf.PointInPolygon.evaluateColumnar(PointInPolygon.java:128)
        at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$4(GpuUserDefinedFunction.scala:60)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:29)
        at com.nvidia.spark.rapids.GpuUserDefinedFunction.$anonfun$columnarEval$2(GpuUserDefinedFunction.scala:58)
        at com.nvidia.spark.rapids.Arm$.withResource(Arm.scala:47)
        at com.nvidia.spark.rapids.GpuUserDefinedFunction.columnarEval(GpuUserDefinedFunction.scala:56)
...
```

1, When building, libcuSpatialjni.so is built/linked against cudf-23.02.0 because of the issue:  https://github.com/rapidsai/cuspatial/pull/932 removed the file “shapefile_reader.hpp” with the cudf  interface, e.g.,  [null_count()](https://github.com/NVIDIA/spark-rapids-examples/blob/branch-23.06/examples/UDF-Examples/Spark-cuSpatial/src/main/native/src/PointInPolygonJni.cpp#L127)
2, When testing, besides cudf 23.02.0 native so, our cuSpatial jar also loads jar file rapids-4-spark_2.12-23.06.0-SNAPSHOT, which introduces cudf 23.06.0  (Mismatching)
3, Last week cudf 23.06.0  removed null_count()  interface via [PR13372](https://github.com/rapidsai/cudf/pull/13372/files#diff-a1f534fce66eaa60ec17a09d951208b8ed426ead5fc61f4453648d56fee58b42R66)
4, Then our cuSpatial app test failed reporting Unsatisfied symbol: null_count() 

**Steps/Code to reproduce bug**
Following : https://github.com/NVIDIA/spark-rapids-examples/blob/main/examples/UDF-Examples/Spark-cuSpatial/README.md

**Expected behavior**
Test Got PASS

**Environment details (please complete the following information)**
 - Spark standalone, or Yarn cluster
 - Spark 3.1.x or above

**Comment by nvliyuan** [comment]
close this issue since we target cuSpatial demo test to a specific plugin version
